/**
 * @deprecated V5 (O10): This file is a BACKWARD COMPATIBILITY wrapper.
 * All collection path constants are now defined in schemas.js COLLECTIONS.
 *
 * New code should import directly from:
 *   import { COLLECTIONS } from '../models/schemas';
 *
 * Existing imports continue to work via these re-exports.
 * This file will be removed after all consumers are migrated.
 *
 * @module automation/firestorePaths
 */

import { COLLECTIONS } from '../models/schemas.js';

// ── Re-exports from COLLECTIONS (single source of truth) ──

/** @deprecated Use COLLECTIONS.SETTINGS */
export const SETTINGS_COLLECTION = COLLECTIONS.SETTINGS;

/** Settings document IDs (not in COLLECTIONS — these are doc-level) */
export const SETTINGS_DOCS = {
    AUTOMATION_CORE: 'automationCore',
    TELEGRAM_OPS: 'telegramOps',
    AUTOMATION_AI: 'automationAI',
};

/** @deprecated Use COLLECTIONS.AUTOMATION_ROUTINES */
export const AUTOMATION_ROUTINES = COLLECTIONS.AUTOMATION_ROUTINES;

/** @deprecated Use COLLECTIONS.AUTOMATION_RUNS */
export const AUTOMATION_RUNS = COLLECTIONS.AUTOMATION_RUNS;

/** @deprecated Use COLLECTIONS.AUTOMATION_METRICS_DAILY */
export const AUTOMATION_METRICS_DAILY = COLLECTIONS.AUTOMATION_METRICS_DAILY;

/** @deprecated Use COLLECTIONS.OPERATION_INCIDENTS */
export const OPERATION_INCIDENTS = COLLECTIONS.OPERATION_INCIDENTS;

/** @deprecated Use COLLECTIONS.AI_EXECUTIONS */
export const AI_EXECUTIONS = COLLECTIONS.AI_EXECUTIONS;

/** @deprecated Use COLLECTIONS.TELEGRAM_SESSIONS */
export const TELEGRAM_SESSIONS = COLLECTIONS.TELEGRAM_SESSIONS;

/** @deprecated Use COLLECTIONS.TELEGRAM_REPORTS */
export const TELEGRAM_REPORTS = COLLECTIONS.TELEGRAM_REPORTS;

/** @deprecated Use COLLECTIONS.TELEGRAM_ESCALATIONS */
export const TELEGRAM_ESCALATIONS = COLLECTIONS.TELEGRAM_ESCALATIONS;

/** @deprecated Use COLLECTIONS.TELEGRAM_BOT_LOGS */
export const TELEGRAM_BOT_LOGS = COLLECTIONS.TELEGRAM_BOT_LOGS;

/** @deprecated Use COLLECTIONS.TELEGRAM_DELIVERIES */
export const TELEGRAM_DELIVERIES = COLLECTIONS.TELEGRAM_DELIVERIES;

// ── Analytics Engine ──
export const OPERATIONAL_KPI_SNAPSHOTS = COLLECTIONS.OPERATIONAL_KPI_SNAPSHOTS;
export const USER_OPERATIONAL_SCORES = COLLECTIONS.USER_OPERATIONAL_SCORES;
export const ROUTINE_OPERATIONAL_SCORES = COLLECTIONS.ROUTINE_OPERATIONAL_SCORES;
export const TEAM_OPERATIONAL_SUMMARIES = COLLECTIONS.TEAM_OPERATIONAL_SUMMARIES;
export const OPERATIONAL_RISK_FLAGS = COLLECTIONS.OPERATIONAL_RISK_FLAGS;
export const OPERATIONAL_RECOMMENDATIONS = COLLECTIONS.OPERATIONAL_RECOMMENDATIONS;
export const ANALYTICS_REFRESH_LOGS = COLLECTIONS.ANALYTICS_REFRESH_LOGS;

// ── Optimization Engine ──
export const OPTIMIZATION_OPPORTUNITIES = COLLECTIONS.OPTIMIZATION_OPPORTUNITIES;
export const OPTIMIZATION_SIMULATIONS = COLLECTIONS.OPTIMIZATION_SIMULATIONS;
export const OPERATIONAL_PLANS = COLLECTIONS.OPERATIONAL_PLANS;
export const APPLIED_RECOMMENDATIONS = COLLECTIONS.APPLIED_RECOMMENDATIONS;
export const OPTIMIZATION_HISTORY = COLLECTIONS.OPTIMIZATION_HISTORY;

// ── Convenience: re-export the full array ──
export const ALL_AUTOMATION_COLLECTIONS = [
    AUTOMATION_ROUTINES,
    AUTOMATION_RUNS,
    AUTOMATION_METRICS_DAILY,
    OPERATION_INCIDENTS,
    AI_EXECUTIONS,
    TELEGRAM_SESSIONS,
    TELEGRAM_REPORTS,
    TELEGRAM_ESCALATIONS,
    TELEGRAM_BOT_LOGS,
    TELEGRAM_DELIVERIES,
    OPERATIONAL_KPI_SNAPSHOTS,
    USER_OPERATIONAL_SCORES,
    ROUTINE_OPERATIONAL_SCORES,
    TEAM_OPERATIONAL_SUMMARIES,
    OPERATIONAL_RISK_FLAGS,
    OPERATIONAL_RECOMMENDATIONS,
    ANALYTICS_REFRESH_LOGS,
    OPTIMIZATION_OPPORTUNITIES,
    OPTIMIZATION_SIMULATIONS,
    OPERATIONAL_PLANS,
    APPLIED_RECOMMENDATIONS,
    OPTIMIZATION_HISTORY,
];
